version: '3'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.backend
    container_name: backend_container
    ports:
      - "8090:8090"

  web:
    build:
      context: web
      dockerfile: Dockerfile.web
    container_name: web_container
    ports:
      - "8081:8081"
